# Generated by Django 4.2 on 2023-04-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
